import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.tasks.KotlinJvmCompile

plugins {
    id "org.jetbrains.kotlin.jvm"
}

def javaExtension = extensions.getByType(JavaPluginExtension)
def kotlinJvmTarget = providers.provider {
    def toolchainLanguageVersion = javaExtension.toolchain.languageVersion.orNull?.asInt()
    def javaTargetVersion = toolchainLanguageVersion ?: javaExtension.targetCompatibility.majorVersion
    JvmTarget.fromTarget(javaTargetVersion.toString())
}

tasks.withType(KotlinJvmCompile).configureEach {
    compilerOptions.jvmTarget.set(kotlinJvmTarget)
}

kotlin {
    kotlinDaemonJvmArgs = ["--add-opens=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED",
                           "--add-opens=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED",
                           "--add-opens=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED",
                           "--add-opens=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED",
                           "--add-opens=jdk.compiler/com.sun.tools.javac.jvm=ALL-UNNAMED",
                           "--add-opens=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED",
                           "--add-opens=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED",
                           "--add-opens=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED",
                           "--add-opens=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED",
                           "--add-opens=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED"]
}
