plugins {
    id "io.micronaut.build.internal.r2dbc-dependencies"
    id "java"
    id "com.adarshr.test-logger"
    id "io.micronaut.application"
    id "io.micronaut.test-resources"
    id "io.micronaut.build.internal.java-base"
}

group "io.micronaut.example"

micronaut {
    importMicronautPlatform = false
    version libs.versions.micronaut.platform.get()
    runtime "netty"
    testRuntime "junit"
    testResources {
        clientTimeout = 300
        version = libs.versions.micronaut.test.resources.get()
    }
}

testlogger {
    showFullStackTraces true
}

application {
    mainClass = "testgraalvm.Application"
}

dependencies {
    micronautBoms(platform(mnData.micronaut.data.bom))
    micronautBoms(platform(mnSerde.micronaut.serde.bom))
    annotationProcessor(mn.micronaut.graal)
    runtimeOnly(mnSql.micronaut.jdbc.hikari)
    runtimeOnly(mnLogging.logback.classic)

    implementation(mn.micronaut.http.client)
    implementation projects.micronautR2dbcCore
    implementation(mnData.micronaut.data.r2dbc) {
        exclude module:'micronaut-r2dbc-core'
    }
    implementation(mnSerde.micronaut.serde.jackson)

    implementation projects.micronautTestGraalvm.micronautCommon
    testImplementation projects.micronautTestGraalvm.micronautCommonTests
    testImplementation(mnTest.micronaut.test.core)
    testImplementation(libs.junit.platform.engine)
    runtimeOnly mn.snakeyaml
}

configurations.all {
    resolutionStrategy.preferProjectModules()
}

graalvmNative {
    toolchainDetection = false
    binaries {
        all {
            buildArgs.add("--report-unsupported-elements-at-runtime")
            if (System.getenv("GRAALVM_HOME")?.contains("graal") && System.getenv("GRAALVM_HOME")?.contains("25")) {
                logger.quiet("Enabling SharedArenaSupport for GraalVM 25")
                buildArgs.add("-H:+SharedArenaSupport")
            }
        }
    }
    metadataRepository {
        enabled = true
    }
}
