plugins {
    id("io.micronaut.build.internal.kotlin-kapt")
    id "io.micronaut.build.internal.r2dbc-example"
}

compileKotlin {
    kotlinOptions {
        freeCompilerArgs = ["-Xjvm-default=all"]
    }
}

compileTestKotlin {
    kotlinOptions {
        freeCompilerArgs = ["-Xjvm-default=all"]
    }
}
