plugins {
    id "io.micronaut.build.internal.r2dbc-kotlin-example"
    id("io.micronaut.build.internal.kotlin-kapt")
}

dependencies {
    kapt(mnData.micronaut.data.processor)
    implementation mnKotlin.micronaut.kotlin.runtime
    testImplementation(libs.junit.platform.engine)
}

application {
    mainClass = "example.ApplicationKt"
}
