[versions]
micronaut = "3.4.3"
micronaut-docs = "2.0.0"

groovy = "3.0.10"
managed-testcontainers = "1.17.3"

h2 = "1.4.200"
ojdbc11 = "21.6.0.0.1"

# R2DBC Drivers
managed-r2dbc = "1.0.0.RELEASE"
managed-r2dbc-pool = "0.9.1.RELEASE"

managed-r2dbc-oracle = "0.4.0"
managed-r2dbc-mysql = "0.8.2.RELEASE"
managed-r2dbc-h2 = "0.8.5.RELEASE"
managed-r2dbc-mariadb = "1.1.2"
managed-r2dbc-postgresql = "0.9.2.RELEASE"
managed-r2dbc-mssql = "0.9.0.RELEASE"

[libraries]
managed-r2dbc-spi = { module = "io.r2dbc:r2dbc-spi", version.ref = "managed-r2dbc" }
managed-r2dbc-pool = { module = "io.r2dbc:r2dbc-pool", version.ref = "managed-r2dbc-pool" }

# R2DBC Drivers
managed-r2dbc-h2 = { module = "io.r2dbc:r2dbc-h2", version.ref = "managed-r2dbc-h2" }
managed-r2dbc-oracle = { module = "com.oracle.database.r2dbc:oracle-r2dbc", version.ref = "managed-r2dbc-oracle" }
managed-r2dbc-mariadb = { module = "org.mariadb:r2dbc-mariadb", version.ref = "managed-r2dbc-mariadb" }
managed-r2dbc-mysql = { module = "dev.miku:r2dbc-mysql", version.ref = "managed-r2dbc-mysql" }
managed-r2dbc-mssql = { module = "io.r2dbc:r2dbc-mssql", version.ref = "managed-r2dbc-mssql" }
managed-r2dbc-postgresql = { module = "org.postgresql:r2dbc-postgresql", version.ref = "managed-r2dbc-postgresql" }

# JDBC Drivers
mariadb-java-client = { module = "org.mariadb.jdbc:mariadb-java-client" }
mssql-jdbc = { module = "com.microsoft.sqlserver:mssql-jdbc" }
mysql-connector-java = { module = "mysql:mysql-connector-java" }
postgresql = { module = "org.postgresql:postgresql" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
ojdbc11 = { module = "com.oracle.database.jdbc:ojdbc11", version.ref = "ojdbc11" }

flyway-mysql = { module = "org.flywaydb:flyway-mysql" }

# BOMs
boms-testcontainers = { module = "org.testcontainers:testcontainers-bom", version.ref = "managed-testcontainers" }

testcontainers-jdbc = { module = "org.testcontainers:jdbc" }
testcontainers-mariadb = { module = "org.testcontainers:mariadb" }
testcontainers-mssqlserver = { module = "org.testcontainers:mssqlserver" }
testcontainers-mysql = { module = "org.testcontainers:mysql" }
testcontainers-oracle = { module = "org.testcontainers:oracle-xe" }
testcontainers-postgresql = { module = "org.testcontainers:postgresql" }
testcontainers-r2dbc = { module = "org.testcontainers:r2dbc" }
testcontainers-spock = { module = "org.testcontainers:spock" }
