[versions]
managed-r2dbc-maria = "1.0.3"
managed-r2dbc-oracle = "0.2.0"
managed-reactor-netty = "1.0.19"
managed-r2dbc = "Arabba-SR11"
managed-testcontainers = "1.16.2"

jakarta-inject-api = "2.0.0"
h2 = "1.4.200"
ojdbc11 = "21.1.0.0"

# Micronaut
micronaut-data = "3.2.1"
micronaut-test = "3.1.1"


[libraries]
managed-r2dbc-mariadb = { module = "org.mariadb:r2dbc-mariadb", version.ref = "managed-r2dbc-maria" }
managed-r2dbc-oracle = { module = "com.oracle.database.r2dbc:oracle-r2dbc", version.ref = "managed-r2dbc-oracle" }
managed-reactor-netty = { module = "io.projectreactor.netty:reactor-netty", version.ref = "managed-reactor-netty" }

# BOMs
boms-r2dbc = { module = "io.r2dbc:r2dbc-bom", version.ref = "managed-r2dbc" }
boms-testcontainers = { module = "org.testcontainers:testcontainers-bom", version.ref = "managed-testcontainers" }

# Micronaut
micronaut-data-processor = { module = "io.micronaut.data:micronaut-data-processor", version.ref = "micronaut-data" }
micronaut-flyway = { module = "io.micronaut.flyway:micronaut-flyway" }
micronaut-graal = { module = "io.micronaut:micronaut-graal" }
micronaut-http-client = { module = "io.micronaut:micronaut-http-client" }
micronaut-inject = { module = "io.micronaut:micronaut-inject" }
micronaut-jdbc-hikari = { module = "io.micronaut.sql:micronaut-jdbc-hikari" }
micronaut-management = { module = "io.micronaut:micronaut-management" }
micronaut-test-core = { module = "io.micronaut.test:micronaut-test-core" }
micronaut-validation = { module = "io.micronaut:micronaut-validation" }
micronaut-data-r2dbc = { module = "io.micronaut.data:micronaut-data-r2dbc", version.ref = "micronaut-data" }

graal = { module = "org.graalvm.nativeimage:svm" }
jakarta-inject-api = { module = "jakarta.inject:jakarta.inject-api", version.ref = "jakarta-inject-api" }
mariadb-java-client = { module = "org.mariadb.jdbc:mariadb-java-client" }
mssql-jdbc = { module = "com.microsoft.sqlserver:mssql-jdbc" }
mysql-connector-java = { module = "mysql:mysql-connector-java" }
postgresql = { module = "org.postgresql:postgresql" }
r2dbc-h2 = { module = "io.r2dbc:r2dbc-h2" }
r2dbc-mssql = { module = "io.r2dbc:r2dbc-mssql" }
r2dbc-mysql = { module = "dev.miku:r2dbc-mysql" }
r2dbc-postgresql = { module = "io.r2dbc:r2dbc-postgresql" }
r2dbc-spi = { module = "io.r2dbc:r2dbc-spi" }
reactor-core = { module = "io.projectreactor:reactor-core" }
rxjava2 = { module = "io.reactivex.rxjava2:rxjava" }
flyway-mysql = { module = "org.flywaydb:flyway-mysql" }
testcontainers-jdbc = { module = "org.testcontainers:jdbc" }
testcontainers-mariadb = { module = "org.testcontainers:mariadb" }
testcontainers-mssqlserver = { module = "org.testcontainers:mssqlserver" }
testcontainers-mysql = { module = "org.testcontainers:mysql" }
testcontainers-oracle-xe = { module = "org.testcontainers:oracle-xe" }
testcontainers-postgresql = { module = "org.testcontainers:postgresql" }
testcontainers-r2dbc = { module = "org.testcontainers:r2dbc" }
testcontainers-spock = { module = "org.testcontainers:spock" }
logback-classic = { module = "ch.qos.logback:logback-classic" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
ojdbc11 = { module = "com.oracle.database.jdbc:ojdbc11", version.ref = "ojdbc11" }
